# Keep Theme Configuration
base_info:
  primary_color: "#f1c40f"      # Theme color in hex, rgb, or rgba
  title: Luke's Blog            # Website title
  author: Luke                  # Author name
  avatar: /images/avatar.jpg    # Author avatar image path
  logo: /images/logo.jpg        # Website logo path
  favicon: /images/favicon.jpg  # Favicon path
  mode: auto                   # Theme mode: auto (light/dark based on system preference)

menu:
  home: / || fa-solid fa-home # Home page link
  archives: /archives || fa-solid fa-box-archive # Archive page link
  # tags: /tags || fa-solid fa-tags # Tags page link
  # categories: /categories || fa-solid fa-layer-group # Categories page link
  # links: /links || fa-solid fa-link # Links page link
  about: /about || fa-solid fa-user-graduate # About page link
  # photos: /photos || fa-solid fa-image # Photos page link
  # search: /search || fa-solid fa-magnifying-glass # Search page link

first_screen:
  enable: true        # Option values: true | false
  # background_img: /images/bg.svg
  # background_img_dark: /images/bg.svg
  description: Hi, I'm Luke!
  hitokoto: false      # Option values: true | false