name: Deploy Draft

on:
  push:
    branches:
      - draft

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install hexo-cli -g

    - name: Build site with draft base URL
      run: |
        echo "url: https://wulukewu.github.io/blog-draft/" >> _config.yml
        hexo generate

    - name: Deploy to blog-draft
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        external_repository: wulukewu/blog-draft
